# Generated by Django 5.1.4 on 2024-12-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_offers_alter_category_cat_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='offer_name',
            field=models.CharField(default='Default Offer Name', max_length=20),
        ),
    ]
