# Generated by Django 5.1.4 on 2024-12-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productcategory_productimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_images',
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail1',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail2',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail3',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
